name: Deploy Telecom Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS \
          --password-stdin 922778709371.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64 -t telecom-backend:latest .

      - name: Tag Image
        run: |
          docker tag telecom-backend:latest \
          922778709371.dkr.ecr.eu-north-1.amazonaws.com/telecom-backend:latest

      - name: Push Image to ECR
        run: |
          docker push 922778709371.dkr.ecr.eu-north-1.amazonaws.com/telecom-backend:latest

      - name: Deploy on EC2
        uses: webfactory/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          ssh-key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30s
          command_timeout: 10m
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,MONGO_URI,JWT_SECRET
          script: |
            # Authenticate Docker with ECR on EC2 instance
            aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS \
            --password-stdin 922778709371.dkr.ecr.eu-north-1.amazonaws.com
            
            docker pull 922778709371.dkr.ecr.eu-north-1.amazonaws.com/telecom-backend:latest
            docker stop telecom-backend || true
            docker rm telecom-backend || true
            docker run -d \
              --name telecom-backend \
              -p 3002:3002 \
              -e MONGO_URI="${MONGO_URI}" \
              -e JWT_SECRET="${JWT_SECRET}" \
              -e PORT=3002 \
              922778709371.dkr.ecr.eu-north-1.amazonaws.com/telecom-backend:latest